### PR TITLE
Skip appveyor

### PR DESCRIPTION
**Pull request by BoPeng**
Checklist
* [ x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ x] Bumped the build number (if the version is unchanged)
* [ x] Reset the build number to `0` (if the version changed)
* [ x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by BoPeng** [comment]
@conda-forge-admin please rerender

**Comment by BoPeng** [comment]
> RuntimeError: This PR needs a rerender to switch from appveyor to azure

Not sure what this means. @conda-forge/help-python , could you help?

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
See https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-rerender

**Comment by BoPeng** [comment]
I used the command, and I have "Allow edits from maintainers." selected, but the problem persists. Perhaps I should try to command line method.

**Pull request merged**
